# Generated by Django 6.0.3 on 2026-04-17 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payments_link_payments_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
