# Generated by Django 6.0.3 on 2026-04-19 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_course_owner_lesson_owner'),
        ('users', '0006_alter_payments_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'платежы'},
        ),
        migrations.RemoveField(
            model_name='payments',
            name='paid_course',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='payments',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_course', to='materials.course', verbose_name='курс на оплату'),
        ),
        migrations.AddField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата создания продукта'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='link',
            field=models.URLField(blank=True, help_text='укажите ссылку на оплату', max_length=400, null=True, verbose_name='ссылка на платеж'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_lesson', to='materials.lesson', verbose_name='урок на оплату'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('наличные', 'Cash'), ('перевод на карту', 'Card')], max_length=20, null=True, verbose_name='способ платежа: наличные или перевод на счет'),
        ),
    ]
