# Generated by Django 6.0.3 on 2026-04-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_payments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id продукта'),
        ),
    ]
