# Generated by Django 6.0.3 on 2026-04-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_payments_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id цены'),
        ),
    ]
