# Generated by Django 6.0.3 on 2026-04-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_payments_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='валюта'),
        ),
    ]
