# Generated by Django 6.0.3 on 2026-04-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_payments_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='currency',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='link',
            field=models.URLField(blank=True, help_text='укажите ссылку на оплату', max_length=500, null=True, verbose_name='ссылка на платеж'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='price_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='id цены'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='id продукта'),
        ),
    ]
