# Generated by Django 6.0.3 on 2026-04-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_payments_currency_alter_payments_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания продукта'),
        ),
    ]
